---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Страницы должны загружаться не дольше 2–3 секунд (включая мобильные устройства)
  - При высокой нагрузке вместо ошибки 500/503 должна отображаться «очередь» или другое дружелюбное сообщение
  - Изображения товаров должны быть оптимизированы (ленивая загрузка, WebP-формат)
  - Данные платежей (например, CVV, номера карт) не должны сохраняться в логах
  - Сессии пользователей должны автоматически завершаться после длительного бездействия
  - Все формы должны быть защищены от SQL-инъекций и XSS-атак
  - Админ-панель должна быть доступна только по VPN или с двухфакторной аутентификацией
  - Корзина не должна сбрасываться после обновления страницы или перезахода в аккаунт
  - Поиск должен учитывать опечатки и предлагать исправления (например, «айфон» → «iPhone»)
  - Фильтры должны сохраняться при возврате на страницу категории
  - Если товара нет в наличии, пользователь должен видеть это до добавления в корзину
  - Мобильная версия должна быть полнофункциональной (без "обрезанных" элементов, удобные тапы)
  - На разных разрешениях (от 320px до 4K) не должно быть горизонтального скролла
  - Переключение языка должно сохраняться при переходе между страницами
  - Если перевод отсутствует, должен подставляться язык по умолчанию (без ошибок 404)
  - Цены в корзине и при оформлении заказа должны автоматически обновляться при изменении акций или скидок
  - При отмене заказа товары должны возвращаться в доступный остаток
  - Если товар удален из корзины (например, закончился), пользователь должен получить уведомление
  - В странах с GDPR должна быть возможность скачивания/удаления данных пользователя
  - Даты, валюты, единицы измерения должны автоматически подстраиваться под регион
  - Заказы, оформленные во время сбоя платежной системы, не должны теряться
  - При восстановлении из бэкапа не должно возникать дублирующихся заказов
  - Ошибки 404/500 должны вести на кастомные страницы с полезными ссылками
  - Критические ошибки (например, падение корзины) должны логироваться и отправляться в мониторинг (Sentry, Grafana и т. д.)
  - Администратор должен получать уведомления о неудачных попытках входа в админ-панель
