---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность регистрации и входа в аккаунт
  - При регистрации пользователю нужно вводить номер телефона и пароль
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Страницы должны загружаться не дольше 2–3 секунд (включая мобильные устройства)
  - При высокой нагрузке вместо ошибки 500/503 должна отображаться «очередь» или другое дружелюбное сообщение
  - Изображения товаров должны быть оптимизированы (ленивая загрузка, WebP-формат)
  - Все формы должны быть защищены от SQL-инъекций и XSS-атак
  - Корзина не должна сбрасываться после обновления страницы или перезахода в аккаунт
  - Поиск должен учитывать опечатки и предлагать исправления (например, «айфон» → «iPhone»)
  - Фильтры должны сохраняться при возврате на страницу категории
  - Если товара нет в наличии, пользователь должен видеть это до добавления в корзину
  - Мобильная версия должна быть полнофункциональной (без "обрезанных" элементов, удобные тапы)
  - На разных разрешениях (от 320px до 4K) не должно быть горизонтального скролла
  - Переключение языка должно сохраняться при переходе между страницами
  - Если перевод отсутствует, должен подставляться язык по умолчанию (без ошибок 404)
  - Цены в корзине и при оформлении заказа должны автоматически обновляться при изменении акций или скидок
  - При отмене заказа товары должны возвращаться в доступный остаток
  - Если товар удален из корзины, пользователь должен получить уведомление
  - При удалении товара из корзины пользователь должен получить предупреждение об удалении
  - После оформления заказа, товары удаляются из корзины
  - В странах с GDPR должна быть возможность скачивания/удаления данных пользователя
  - Даты, валюты, единицы измерения должны автоматически подстраиваться под регион
  - Заказы, оформленные во время сбоя платежной системы, не должны теряться
  - При восстановлении из бэкапа не должно возникать дублирующихся заказов
  - Символы при вводе пароля должны автоматически заменяться на знак "*"
  - Телефон должен вводиться в определённом формате (начиная с "+" и отсутствием возможности ввода других символов кроме цифр)
